sudo: true
language: node_js
node_js:
  - "8"
git:
    quiet: true
cache: npm
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@138.68.71.197:~/www/test/
