sudo: true
language: node_js
node_js:
  - "8"
git:
    quiet: true
cache: npm
stages:
  - transpile
  - name: deploy
      if: branch = master
jobs:
  - stage: transpile
    script: npm run build:prod
  - stage: deploy
    script: ./deploy.sh

