sudo: true
language: node_js
node_js:
  - "8"
git:
    quiet: true
cache: npm
after_success:
  - rsync -rq --delete --rsync-path="mkdir -p ~/www/test/ && rsync" \
    $TRAVIS_BUILD_DIR/dist travis@138.68.71.197:~/www/test/
