sudo: true
language: node_js
node_js:
  - "8"
git:
  quiet: true
cache: npm
before_install:
  - openssl aes-256-cbc -K $encrypted_47e438c158bc_key -iv 0 -p
    -in deploy_rsa.enc -out deploy_rsa -d
  - chmod 600 deploy_rsa
  - mv deploy_rsa ~/.ssh/id_rsa
  - cat server.pub >> $HOME/.ssh/known_hosts
notifications:
  email: false
after_success:
    - bash ./deploy.sh

