sudo: true
language: node_js
node_js:
  - "8"
git:
  quiet: true
cache: npm
script:
  - echo $TRAVIS_BRANCH
  - $TRAVIS_BUILD_DIR
before_install:
  - openssl aes-256-cbc -K $encrypted_47e438c158bc_key -iv $encrypted_47e438c158bc_iv
    -in deploy_dev_rsa.enc -out deploy_dev_rsa -d
  - chmod 600 deploy_dev_rsa
  - mv deploy_dev_rsa ~/.ssh/id_rsa
  - cat server.pub >> $HOME/.ssh/known_hosts
notifications:
  email: false
after_success:
  - bash ./deploy.sh
