export const FETCHING_CLAIMS = 'FETCHING_CLAIMS';
export const FETCHING_CLAIMS_ERROR = 'FETCHING_CLAIMS_ERROR';
export const FETCHING_CLAIMS_SUCCESS = 'FETCHING_CLAIMS_SUCCESS';
export const CREATE_CLAIM_SUCCESS = 'CREATE_CLAIM_SUCCESS';
