export const FETCHING_EMITTED_CLAIMS = 'FETCHING_CLAIMS';
export const FETCHING_EMITTED_CLAIMS_ERROR = 'FETCHING_CLAIMS_ERROR';
export const FETCHING_EMITTED_CLAIMS_SUCCESS = 'FETCHING_CLAIMS_SUCCESS';
export const FETCHING_RECEIVED_CLAIMS = 'FETCHING_CLAIMS';
export const FETCHING_RECEIVED_CLAIMS_ERROR = 'FETCHING_CLAIMS_ERROR';
export const FETCHING_RECEIVED_CLAIMS_SUCCESS = 'FETCHING_CLAIMS_SUCCESS';
