export const FETCHING_FORMS = 'FETCHING_FORMS';
export const FETCHING_FORMS_ERROR = 'FETCHING_FORMS_ERROR';
export const FETCHING_FORMS_SUCCESS = 'FETCHING_FORMS_SUCCESS';
export const UPDATE_PASSPHRASE_FORM = 'UPDATE_PASSPHRASE_FORM';
export const UPDATE_IDENTITY_NAME_FORM = 'UPDATE_IDENTITY_NAME_FORM';
