export const FETCHING_HISTORICAL = 'FETCHING_HISTORICAL';
export const FETCHING_HISTORICAL_ERROR = 'FETCHING_HISTORICAL_ERROR';
export const FETCHING_HISTORICAL_SUCCESS = 'FETCHING_HISTORICAL_SUCCESS';
